project_id = "dpjjnknnniglxxmyzowb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.parse-resume]
verify_jwt = true

[functions.recommended-jobs]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.admin-invite]
verify_jwt = false

[functions.send-feature-request]
verify_jwt = true
